# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json

language: en-US
tone_instructions: provide comments in the voice of David Attenborough
early_access: false
enable_free_tier: true
reviews:
 	profile: chill
 	request_changes_workflow: false
 	high_level_summary: true
 	high_level_summary_placeholder: @coderabbitai summary
 	high_level_summary_in_walkthrough: false
auto_title_placeholder: @coderabbitai
auto_title_instructions: 
review_status: true
 	commit_status: true
 	fail_commit_status: false
 	collapse_walkthrough: false
changed_files_summary: true
 	sequence_diagrams: true
 	assess_linked_issues: true
 	related_issues: true
 	related_prs: true
 	suggested_labels: true
 	auto_apply_labels: false
 	suggested_reviewers: true
 	auto_assign_reviewers: false
 	poem: true
 	labeling_instructions: 
		- label: 
		- instructions: 
 	path_filters: 
 	path_instructions: true
 		- path:
 		- instructions: 
 	abort_on_close: true
 	disable_cache: false
 auto_review: 
enabled: true
auto_incremental_review: true
ignore_title_keywords: 
labels: 
drafts: false
base_branches: cursor-test
finishing_touches:
	docstrings:
		enabled: trrue
	unit_tests:
		enabled: true
tools:
	ast-grep:
		rule_dirs:
		util_dirs:
		essential_rules: true
		packages: 
	shellcheck: 
		enabled: true
	ruff:
		enabled: true
	markdownlint:
		enabled: true
	github-checks:
		enabled: true
		timeout_ms: 90000
	languagetool:
		enabled: true
		enabled_rules: 
		disabled_rules:
		enabled_categories:
		disabled_categories:
		enabled_only: false
		level: default
	biome:
		enabled: true
	hadolint:
		enabled: true
	swiftlint:
		enabled: true
		config_file:
	phpstan:
		enabled: true
		level: default
	golangci-lint:
		enabled: true
		config_file:
	yamllint:
		enabled: true
	gitleaks:
		enabled: true
	checkov:
		enabled: true
	detekt:
		enabled: true
		config_file:
	eslint:
		enabled: true
	rubocop:
		enabled: true
	buf:
		enabled: true
	regal:
		enabled: true
	actionlint:
		enabled: true
	pmd:
		enabled: true
		config_file:
	cppcheck:
		enabled: true
	semgrep:
		enabled: true
		config_file:
	circleci:
		enabled: true
	sqlfluff:
		enabled: true
	prismaLint:
		enabled: true
	oxc:
		enabled: true
	shopifyThemeCheck:
		enabled: true
	luacheck:
		enabled: true
chat:
	auto_reply: true
	integrations:
		jira:
			usage: auto
		linear:
			usage: auto
knowledge_base:
	opt_out: false
	web_search: enabled
	learnings:
		scope: auto
	issues:
		scope: auto
	jira:
		usage: auto
		project_keys:
	linear:
		usage: auto
		team_keys:
pull_requests:
		scope: auto
code_generation:
	docstrings:
		language: en-US
	path_instructions:
		- path:
		- instructions: 
	unit_tests:
path_instructions: 
- path:
- instructions:
